### ISSUE TITLE
Missing CRD `FluxDeployer` at `kubernetes/podify-walkthrough/platform/ocm` ? 

### ISSUE THREAD

**Issue by sk31337** [open-component-model/ocm-examples#18]
After following https://github.com/open-component-model/ocm-examples/tree/main/kubernetes/podify-walkthrough I was able with additional manual steps to deploy ocm-controller on my local kind cluster.

```
kubectl get deploy -n ocm-system
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
ocm-controller        0/1     1            0           61s
registry              1/1     1            1           58s
unpacker-controller   1/1     1            1           2m6s

# pod logs of ocm-controller
2024-03-06T15:50:48Z	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2024-03-06T15:50:48Z	ERROR	setup	unable to create controller	{"controller": "FluxDeployer", "error": "failed setting index fields: no matches for kind \"FluxDeployer\" in version \"delivery.ocm.software/v1alpha1\""}
main.setupManagers
	/home/runner/work/ocm-controller/ocm-controller/main.go:265
main.main
	/home/runner/work/ocm-controller/ocm-controller/main.go:135
runtime.main
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/proc.go:267
```

Is the following CRD missing at `kubernetes/podify-walkthrough/platform/ocm` which I found in https://github.com/open-component-model/demo-secure-delivery/blob/main/00-setup-demo/manifests/ocm.yaml ?

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ocm-system
    app.kubernetes.io/part-of: ocm
  name: fluxdeployers.delivery.ocm.software
spec:
  group: delivery.ocm.software
  names:
    kind: FluxDeployer
    listKind: FluxDeployerList
    plural: fluxdeployers
[....]
```
